### ISSUE TITLE
Not working with remote image URLs

### ISSUE THREAD

**Issue by ezequias** [gruehle/MarkdownPreview#100]
Markdown preview is not working with remote repositories for images. 

Why does this behavior is occurring?

**Comment by gruehle** [comment]
@ezequias Can you give an example? External images are working fine for me.

**Comment by ezequias** [comment]
@gruehle try this out:
![logo](https://app.box.com/representation/file_version_162268617121/image_2048/1.png)

**Comment by ezequias** [comment]
O noticed what was happening. I was using a box.com https image url and it only worked at the browser. Thanks for the question. With google drive it does work properly. Here is the new link:

![logo](https://lh5.googleusercontent.com/e7oTpfbieAUduD-pRdsIXeCa6Wbx4yu5oNTSsvAMaskVmn4sj7cwhb2mePRqPg7G4UHNeDUTQPz-inY=w1366-h662-rw)

**Comment by gruehle** [comment]
Thanks for the follow up. It looks like you've got everything worked out, so I'm going to close this bug. Please let me know if you run into any other issues.
