### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by twhite313** [gruehle/MarkdownPreview#102]
Tried installing on a clean install of Brackets 1.9 (build 1.9.0-17312) and received the "Installation failed" message. 
![screen shot 2017-04-17 at 3 28 57 pm](https://cloud.githubusercontent.com/assets/26779414/25107245/0d52d036-2383-11e7-9ce8-1e9feeb8d4f6.png)

Brackets 1.9
macOS Sierra 10.12.4

**Comment by twhite313** [comment]
Just confirmed that it is running on my other machine with Brackets 1.8

**Comment by twhite313** [comment]
Restarting Brackets fixed the issue. Not ideal -- it should install without a restart -- but it did work.

**Comment by gruehle** [comment]
@tim-white-esri thanks for the update. What platform/OS are you using? I just tried on OSX 10.12, and the installation worked fine without a restart.

**Comment by twhite313** [comment]
Its in my original post: macOS Sierra 10.12.4, Brackets 1.9 (build 1.9.0-17312). Running on a mid-2015 MacBook Pro.

After restarting Brackets, everything was fine.
