### ISSUE TITLE
Markdown Extra as an Option

### ISSUE THREAD

**Issue by D-Marc1** [gruehle/MarkdownPreview#109]
Would you ever consider Markdown Extra as an option for this plugin? It would be an awesome addition.

**Comment by gruehle** [comment]
Hey @D-Marc1, thanks for the suggestion! This plugin uses marked.js to parse the markdown content, so it couldn't be added directly to this extension without a substantial re-write. I just don't have the time for that. 

If you or anyone you know would be interested in adding support and submitting a pull request, that would be awesome.
