### ISSUE TITLE
Hide Horizontal Preview: Sub-Option for "Detached Preview": Fixes Brackets No-Vertical (Feature Request)

### ISSUE THREAD

**Issue by washere** [gruehle/MarkdownPreview#111]
**Feature Request:
Show Detached Preview + Hide Horizontal: Fixes Brackets No-Vertical**

This is a wonderful extension. It is lacking only one feature because of Brackets API.

Most Markdown previews (QOwnNotes, BoostNote, MS VS Code, Atom, etc etc) work with Markdown preview as dual vertical panes.

Brackets API does not allow this, so we are stuck  with Horizontal pane windows as preview only.

**WORKAROUND:**

* Open Preview
* Open Detached Preview
* Sub-option under Detached Preview:
       Hide Horizontal (in-app) Bottom Preview Window Pane 

This way we can have 2 windows next to each other: 
Brackets + Detached Preview window
And no dual horizontal preview, which will save a lot of screen space on laptops and ultrabooks.

Some apps work like this. For example iA Writer for Windows  preview launches a new window next to the editor.

It would solve the problem with Brackets API not letting us have vertical preview pane.

I am also opening another issue for sync-scroll of Detached Preview window.

Thanks again.

**Sync-Scroll with Detached Preview Window (Feature Request):**

https://github.com/gruehle/MarkdownPreview/issues/112

**Comment by washere** [comment]
If this is impossible due to API again, at least;

**Make dragging the divider (for 2 window panes) for the bottom preview horizontal pane all the way down (or nearly) to the bottom of editor window pane. So at least it takes minimal space.**

**Comment by gruehle** [comment]
@washere thanks for the feedback! This extension hasn't been updated in over 4 years, and unfortunately I don't have the time to make any more improvements. 

There is another Markdown Preview extension for Brackets that you may want to try: https://bitbucket.org/begue/brackets-markdown-preview. I haven't tried it myself, but it does look like has more features and options.
