### ISSUE TITLE
Sync-Scroll with Detached Preview Window (Feature Request)

### ISSUE THREAD

**Issue by washere** [gruehle/MarkdownPreview#112]
**Feature Request:
Sync-Scroll with Detached Preview Window**

Because Brackets API does not allow us to have vertical scroll preview, like most professional Markdown editors, our best option is a detached preview window next to editor thanks to this wonderful extension.

The only thing is missing that detached preview window does not sync-scroll with the editor like most dual pane md editors.

If this can be done, like iA Writer for Windows which also launches a new window for preview, then this extension becomes a complete answer to Brackets API problems with not allowing vertical preview.

I also opened another issue to have a sub-option to hide the horizontal preview when launching external detached preview linked below.

Thanks again for this great work.

**Hide Horizontal Preview: Sub-Option for "Detached Preview": Fixes Brackets No-Vertical (Feature Request)**
https://github.com/gruehle/MarkdownPreview/issues/111

**Comment by gruehle** [comment]
I'm not sure what you mean by the detached preview window. Having a detached window was a feature request several years ago, but it never did get implemented. Anyway, as mentioned in the other issue, thanks for reporting but I don't have time to make any improvements to this extension. 
I'd be happy to consider pull requests if you want to make the improvements.
