### ISSUE TITLE
No horizontal rule with three hyphens

### ISSUE THREAD

**Issue by ricardograca** [gruehle/MarkdownPreview#29]
When using only three hyphens to produce a HR: `---` there is no HR on the preview.

Using any other allowed character works, e.g.: `___`, `***`.

If using spaces between the hyphens, then the HR appears in the preview: `- - -`, however three consecutive hyphens are valid according to the [Markdown Documentation](http://daringfireball.net/projects/markdown/syntax#hr).

**Comment by gruehle** [comment]
@ricardograca - This was a problem with the marked.js library. The latest version of the extension, 1.0.10, has an updated version of marked.js that fixes this bug.
