### ISSUE TITLE
table not render correctly

### ISSUE THREAD

**Issue by cgcgbcbc** [gruehle/MarkdownPreview#49]
it seems that this form of table is not rendered correctly.
```markdown
header | header | header
--------- | --------- | ---------
text      |  text      | text 
```
it should be:

header | header | header
--------- | --------- | ---------
text      |  text      | text 

but now it is :

![screen shot 2014-06-19 at 21 41 56](https://cloud.githubusercontent.com/assets/3320660/3328030/841f6b34-f7b7-11e3-83b3-1e6fb894943e.png)

table lost its border

**Comment by gruehle** [comment]
This is fixed with the latest version of marked.js that was integrated in version 1.0.10 of the extension.
