### ISSUE TITLE
MdP does not sync scroll position if the editor doesn't scroll

### ISSUE THREAD

**Issue by JeffryBooher** [gruehle/MarkdownPreview#61]
I think I figured out what the steps are to the scrolling issue that I was reporting in #53 which was not a splitview issue after all:

If the editor has enough to make the markdown preview require scrolling to see some lines of markdown but the editor itself doesn't need scrollbars to show all of its content then the markdown preview panel is scrolled back to the top after every change to the document.

1. Create a new md file
1. Turn on MdPreview
1. Resize the MdPreview panel so that it can only show a few lines
1. Add some mark down in the editor 
1. Keep adding mark down until the line you just typed in the editor is not visible in the MdPreview panel
1. Scroll the MdPreview panel to the bottom to see what you just typed
1. Switch back to the editor and add another line of markdown to the end of the document
==> MdPreview panel scrolls back to the top

**Comment by arnisjuraga** [comment]
#65

**Comment by gruehle** [comment]
@JeffryBooher - Thanks for the updated steps. Fixed in c2b8c6abe1b6251ec094f2e32d52fef5303945ef.

@arnisjuraga - Bug #65 was that _all_ scroll syncing was broken. This is a special case where typing was always scrolling to the top. Both have been fixed!
