### ISSUE TITLE
Doesn't sync scroll position

### ISSUE THREAD

**Issue by SenpaiSilver** [gruehle/MarkdownPreview#65]
It seems that no matter what I do the preview won't sync the scroll position.

Writing will also make the preview scroll back to the top.

**Comment by anicething** [comment]
yes, same me

**Comment by arnisjuraga** [comment]
Temprary workaround - to fixed scroll location in preview iframe, 
comment out line 105:

~~~
//$iframe[0].contentDocument.body.scrollTop = scrollTop;
~~~

**Comment by gruehle** [comment]
Fixed in 88fa7f6971b404e6dd2f58d6f01f7c20bc513693, thanks to @peterflynn.
