### ISSUE TITLE
Preview area covered from an overflowing area

### ISSUE THREAD

**Issue by nickast** [gruehle/MarkdownPreview#72]
Hello,

I have just downloaded and install brackets and markdown to try your feature but it seems that is does not work on my side.

Aside from the bottom area flickering constantly I also have a problem with an area appearing on top of the preview and covering everything. See a screenshot attached.

Keep up the good work. I cannot wait to see it working in action! I would love it.
![screen shot 2015-02-07 at 02 57 31](https://cloud.githubusercontent.com/assets/1750172/6089967/7e17a25a-ae74-11e4-82e5-68d5808f0d41.png)

**Comment by petermueller86** [comment]
Same here. Seems to happen just with the latest version of Brackets. I use an older Brackets version at work and on this machine the plugin works.

**Comment by gruehle** [comment]
Yeah, this is a problem with the updated Chromium in the latest brackets shell. I'm working on a fix right now.

**Comment by nickast** [comment]
Thank you very much Gruehle! Looking forward to the fix!

**Comment by gruehle** [comment]
Version 1.0.10 has been posted to the extension registry. Give it a shot and let me know if you're still having any problems. Thanks!

**Comment by nickast** [comment]
Gruehle, tha problem is fixed on my end. Thank you for your excellent work!
