### ISSUE TITLE
Upcoming Lodash 3.x Update

### ISSUE THREAD

**Issue by MarcelGerber** [gruehle/MarkdownPreview#79]
Dear Brackets extension developer,
we're planning to update the version of [Lodash](https://lodash.com) used in Brackets to 3.x (currently, we use 2.4.1).
As we've had a look at your extension, we noticed there's some code that may cause issues while migrating. Thus, we suggest to update your extension so the migration can happen frictionless.
For your extension, we've identified this issue:
[main.js](https://github.com/gruehle/MarkdownPreview/blob/77f8aafb2d933907b28910e413e95efd07f556ae/main.js#L143-L148): `_.template` with more than 1 parameter won't be supported any more. Instead, use the [new syntax](https://lodash.com/docs#template) `_.template(string)(data)`

Further information:
[Lodash compatibility warnings](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings)
[Brackets issue about updating Lodash](https://github.com/adobe/brackets/issues/10550)

**Comment by MarcelGerber** [comment]
Lodash 3.10.0 will be used in the upcoming Brackets release 1.5 (https://github.com/adobe/brackets/pull/11474).
In order for your extension to still function as it should, we advise you, dear extension developer, to update your extension.

**Comment by gruehle** [comment]
Fixed in 351850a0bfd75c9b90adc86a83b85e33ae255fa8
