### ISSUE TITLE
Vertical Split 

### ISSUE THREAD

**Issue by jacabral** [gruehle/MarkdownPreview#89]
In the How to Use section, it states "The panel can be resized vertically." How do I resize the panel vertically?

**Comment by gruehle** [comment]
@jacabral - If you put the mouse pointer at the top of the panel, the cursor will change to a resize cursor. This allows you to adjust the vertical height of the panel. 

That is the only adjustment available at this time. There is another [request](https://github.com/gruehle/MarkdownPreview/issues/31) to offer more placement options like opening in a separate window or placing on the right side of the window.
