### ISSUE TITLE
Feature request - Gitlab flavoured markdown

### ISSUE THREAD

**Issue by wolf99** [gruehle/MarkdownPreview#90]
Hi, 

As per the title, really. Would like to kindly request if Gitlab flavoured markdown support could be added. [https://github.com/gitlabhq/gitlabhq/blob/master/doc/markdown/markdown.md](https://github.com/gitlabhq/gitlabhq/blob/master/doc/markdown/markdown.md)

Thanks!

**Comment by gruehle** [comment]
Thanks for the suggestion!

The extension already supports GitHub flavored markdown, which looks very similar to Gitlab flavored markdown. Click the gear in the upper right corner of the panel to see/change the settings.

Under the hood, the extension uses the excellent [marked](https://github.com/chjj/marked) parser. Adding support for a new markdown format would require changing marked.js, or moving to a different parser. I don't have plans to do either one. 

You could try submitting a feature request to the marked.js project. If it is added there, it will be picked up next time marked.js is integrated into this extension.
