### ISSUE TITLE
[Feature Request] Add option to change preview location

### ISSUE THREAD

**Issue by ghost** [gruehle/MarkdownPreview#95]
It would be great if we could have to option to choose where to display the preview window.
On some modern screens especially those in 21:9 a vertical split would be far better suited than the current system where your markdown is at the top and the preview is below. 
The optimal solution would be some sort of tickbox or menu to choose from Top, Bottom, Left & Right as a position for the preview window. 
If it's possible to change the location of the preview windows through CSS or HTML or something similar I could do that part.

**Comment by gruehle** [comment]
@kevingrahl thanks for the feedback! There have been many requests to dock the preview window to the side instead of the bottom, but unfortunately side panels are not supported in Brackets. See #31 for more commentary.
